### ISSUE TITLE
bug report: page goes blank when accessing kano states

### ISSUE THREAD

**Issue by struckchure** [segunajibola/buscation-app#2]
To reproduce this error;
https://buscation-app.vercel.app/states/Kano

I checked the console, and I'm guessing the data for kano doesn't exist, but the code didn't check if the data exists or not, therefore, an undefined value caused the page not to render properly

**Comment by segunajibola** [comment]
Kano data is empty for tours center. @struckchure can you check if the data exist, if not display a text.

**Comment by struckchure** [comment]
> Kano data is empty for tours center. @struckchure can you check if the data exist, if not display a text.

yeah, I'm checking it out already
